platform :ios, '15.0'

target 'MediafyDemoAppSwift' do
  use_frameworks!

  pod 'Google-Mobile-Ads-SDK'
  pod 'AppLovinSDK'

  pod 'MediafySDK', '2.4.5'
  pod 'MediafyGoogleMobileAdsAdapter', '2.4.5'
  pod 'MediafyAppLovinMAXAdapter', '2.4.5'
end
